#!/usr/bin/env python3
"""
NOMOS NBA QUANT AI — Genetic Evolution Orchestrator
=====================================================
Replaces the basic 4-agent swarm with real genetic evolution.

Architecture:
  - EvolutionLoop: Population of 50 model configs, evolving 24/7
  - LiteLLM Research Agents: Search latest 2026 NBA quant papers & market microstructure
  - Self-Diagnostic: Every 5 generations, detect weaknesses & adapt
  - Gradio Dashboard: Live evolution stats (generation, Brier, ROI, features)

All computation runs on HF Spaces (16GB RAM). VM is for pilotage only.
"""

import os, sys, json, time, threading, subprocess, signal, traceback, shutil
from pathlib import Path
from datetime import datetime, timezone
from collections import deque

import gradio as gr

# ── Config ──
WORKSPACE = Path("/app/workspace")
WORKSPACE.mkdir(parents=True, exist_ok=True)
LOG_DIR = Path("/app/logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR = Path("/app/data")
DATA_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR = DATA_DIR / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# LiteLLM config (S7 proxy — 13-provider fallback)
LITELLM_URL = os.environ.get("LITELLM_URL", "https://lbjlincoln-nomos-rag-engine-7.hf.space")
LITELLM_KEY = os.environ.get("LITELLM_KEY", "sk-litellm-nomos-2026")

# Kimi / Moonshot AI (OpenAI-compatible API — second research agent)
KIMI_API_KEY = os.environ.get("KIMI_API_KEY", "")
KIMI_BASE_URL = os.environ.get("MOONSHOT_BASE_URL", "https://api.moonshot.cn/v1")

# OpenRouter config (free models for OpenClaw agents)
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
OPENROUTER_MODEL_HEALER = os.environ.get("OPENROUTER_MODEL_HEALER", "openrouter/healer-alpha")
OPENROUTER_MODEL_HUNTER = os.environ.get("OPENROUTER_MODEL_HUNTER", "openrouter/hunter-alpha")

# OpenClaw paths
OPENCLAW_DIR = Path("/app/.openclaw")
OPENCLAW_CONFIG = OPENCLAW_DIR / "config.yaml"
OPENCLAW_AGENTS_MD = Path("/app/AGENTS.md")

# ── State ──
evolution_state = {
    "generation": 0,
    "best_brier": 1.0,
    "best_roi": 0.0,
    "best_sharpe": 0.0,
    "best_composite": 0.0,
    "best_model_type": "none",
    "n_features_selected": 0,
    "n_feature_candidates": 0,
    "population_size": 0,
    "status": "INITIALIZING",
    "cycle": 0,
    "games_loaded": 0,
    "diagnostics": [],
    "research_summary": "No research yet",
    "history": [],
    # OpenClaw state
    "openclaw_status": "NOT INITIALIZED",
    "openclaw_agents": {},
    "openclaw_last_research": "None",
    "openclaw_last_odds": "None",
    "openclaw_last_props": "None",
    "openclaw_last_evolution": "None",
    "openclaw_last_run": "Never",
}

# Shared log
improvement_log = deque(maxlen=500)


def log(msg, target="system"):
    ts = datetime.now(timezone.utc).strftime("%H:%M:%S")
    entry = f"[{ts}] {msg}"
    print(entry)
    improvement_log.append(entry)


# ── OpenClaw Integration ──

def setup_openclaw():
    """
    Write OpenClaw config.yaml and AGENTS.md for multi-agent NBA quant setup.
    Called once at startup to ensure config is in place.
    """
    log("[OpenClaw] Setting up configuration...")
    OPENCLAW_DIR.mkdir(parents=True, exist_ok=True)

    # Write config.yaml
    config_yaml = f"""# OpenClaw Configuration — NOMOS NBA QUANT AI
# Auto-generated by orchestrator.py

version: "1.0"
project: nomos-nba-quant

llm:
  provider: openrouter
  api_key: "{OPENROUTER_API_KEY or '$OPENROUTER_API_KEY'}"
  base_url: "{OPENROUTER_BASE_URL}"
  models:
    - name: healer-alpha
      id: "{OPENROUTER_MODEL_HEALER}"
      role: primary
      cost: free
      context_window: 128000
    - name: hunter-alpha
      id: "{OPENROUTER_MODEL_HUNTER}"
      role: secondary
      cost: free
      context_window: 128000
    - name: claude-opus
      id: "anthropic/claude-opus-4-6"
      role: fallback
      cost: premium
      context_window: 200000
  fallback_chain:
    - healer-alpha
    - hunter-alpha
    - claude-opus

agents:
  research:
    name: "Research Agent"
    model: healer-alpha
    schedule: "*/30 * * * *"
    description: "Searches latest NBA quant papers and hedge fund techniques"
  odds:
    name: "Odds Agent"
    model: hunter-alpha
    schedule: "*/30 * * * *"
    description: "Monitors live odds, line movements, steam moves"
  props:
    name: "Props Agent"
    model: healer-alpha
    schedule: "*/30 * * * *"
    description: "Tracks player performance and prop lines"
  evolution:
    name: "Evolution Agent"
    model: healer-alpha
    schedule: "*/30 * * * *"
    description: "Reports on genetic evolution progress"

skills:
  sports-odds:
    name: "Sports Odds Fetcher"
    description: "Fetches live NBA odds from the-odds-api"
    command: "openclaw skill run sports-odds"
    params:
      sport: basketball_nba
      markets: "h2h,spreads,totals"
      regions: us
  nba-stats:
    name: "NBA Stats Fetcher"
    description: "Fetches NBA stats via nba_api"
    command: "openclaw skill run nba-stats"

output:
  directory: "/app/data/results"
  format: json
  prefix: "openclaw-"

logging:
  level: info
  file: "/app/logs/openclaw.log"
"""
    OPENCLAW_CONFIG.write_text(config_yaml)
    log(f"[OpenClaw] Config written to {OPENCLAW_CONFIG}")

    # Copy AGENTS.md to /app/ if it exists in source
    agents_src = Path("/app/AGENTS.md")
    if agents_src.exists():
        log(f"[OpenClaw] AGENTS.md found at {agents_src}")
    else:
        # Write a minimal AGENTS.md inline
        agents_md = """# NOMOS NBA QUANT AI -- Multi-Agent Setup (OpenClaw)

## Agents
1. **Research Agent** - Searches latest NBA quant papers and hedge fund techniques
2. **Odds Agent** - Monitors live odds, line movements, steam moves
3. **Props Agent** - Tracks player performance and prop lines
4. **Evolution Agent** - Reports on genetic evolution progress

## Skills
- **sports-odds**: Fetches live NBA betting odds
- **nba-stats**: Fetches NBA game/player stats

## Models (OpenRouter Free Tier)
- healer-alpha (primary, free)
- hunter-alpha (secondary, free)
- claude-opus-4-6 (fallback, premium)
"""
        agents_src.write_text(agents_md)
        log(f"[OpenClaw] AGENTS.md written to {agents_src}")

    # Update state
    evolution_state["openclaw_status"] = "CONFIGURED"
    evolution_state["openclaw_agents"] = {
        "research": {"status": "READY", "last_run": "Never", "model": OPENROUTER_MODEL_HEALER},
        "odds": {"status": "READY", "last_run": "Never", "model": OPENROUTER_MODEL_HUNTER},
        "props": {"status": "READY", "last_run": "Never", "model": OPENROUTER_MODEL_HEALER},
        "evolution": {"status": "READY", "last_run": "Never", "model": OPENROUTER_MODEL_HEALER},
    }
    log("[OpenClaw] Setup complete. 4 agents configured, 2 skills registered.")
    return True


def run_openclaw_skill(skill_name, args=None):
    """
    Execute an OpenClaw skill via subprocess.
    Falls back to direct API calls if openclaw CLI is not available.

    Args:
        skill_name: Name of the skill (e.g., 'sports-odds', 'nba-stats')
        args: Dict of arguments to pass to the skill

    Returns:
        dict with skill output or error
    """
    log(f"[OpenClaw] Running skill: {skill_name} with args: {args}")
    result = {"skill": skill_name, "timestamp": datetime.now(timezone.utc).isoformat(), "success": False}

    # Try openclaw CLI first
    openclaw_bin = shutil.which("openclaw")
    if openclaw_bin:
        try:
            cmd = [openclaw_bin, "skill", "run", skill_name]
            if args:
                cmd.extend(["--args", json.dumps(args)])
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=60,
                env={**os.environ, "OPENCLAW_CONFIG": str(OPENCLAW_CONFIG)},
            )
            if proc.returncode == 0:
                result["output"] = proc.stdout.strip()
                try:
                    result["data"] = json.loads(proc.stdout)
                except (json.JSONDecodeError, TypeError):
                    result["data"] = proc.stdout.strip()
                result["success"] = True
                log(f"[OpenClaw] Skill {skill_name} completed via CLI")
            else:
                result["error"] = proc.stderr.strip() or f"Exit code {proc.returncode}"
                log(f"[OpenClaw] Skill {skill_name} CLI failed: {result['error'][:200]}")
        except subprocess.TimeoutExpired:
            result["error"] = "Timeout after 60s"
            log(f"[OpenClaw] Skill {skill_name} timed out")
        except FileNotFoundError:
            result["error"] = "openclaw binary not found"
            log(f"[OpenClaw] openclaw binary not found, falling back to direct API")
    else:
        log(f"[OpenClaw] CLI not available, using direct API fallback for {skill_name}")

    # Fallback: direct API implementation for known skills
    if not result["success"]:
        if skill_name == "sports-odds":
            result = _skill_sports_odds_fallback(args or {})
        elif skill_name == "nba-stats":
            result = _skill_nba_stats_fallback(args or {})
        else:
            result["error"] = f"Unknown skill and no CLI: {skill_name}"

    # Save result
    out_file = RESULTS_DIR / f"openclaw-skill-{skill_name}.json"
    out_file.write_text(json.dumps(result, indent=2, default=str))
    return result


def _skill_sports_odds_fallback(args):
    """Fallback: fetch odds via the-odds-api or LiteLLM knowledge."""
    import urllib.request
    log("[OpenClaw] sports-odds fallback: querying via LiteLLM for latest odds analysis")

    system_prompt = """You are a sports betting odds analyst. Provide current NBA odds analysis.
Output JSON with keys: games (list of {home, away, spread, total, moneyline_home, moneyline_away, sharp_action, notes}),
steam_moves (list of recent sharp line movements), market_summary (string)."""

    user_prompt = """Analyze the current NBA betting market. For today's games:
1. What are the key spreads and totals?
2. Any steam moves or sharp action detected?
3. Reverse line movement signals?
4. Which games have the most disagreement between models and market?
Focus on actionable data for a quantitative model."""

    response = call_litellm(system_prompt, user_prompt, model="smart", max_tokens=2000)
    result = {
        "skill": "sports-odds",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "success": bool(response),
        "source": "litellm-fallback",
        "output": response,
    }
    try:
        result["data"] = json.loads(response)
    except (json.JSONDecodeError, TypeError):
        result["data"] = {"raw_analysis": response[:2000] if response else "No response"}
    return result


def _skill_nba_stats_fallback(args):
    """Fallback: fetch NBA stats via nba_api if available."""
    log("[OpenClaw] nba-stats fallback: attempting nba_api")
    result = {
        "skill": "nba-stats",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "success": False,
        "source": "nba_api-fallback",
    }
    try:
        from nba_api.stats.endpoints import ScoreboardV2
        from datetime import date
        scoreboard = ScoreboardV2(game_date=date.today().strftime("%m/%d/%Y"))
        games = scoreboard.get_normalized_dict()
        result["data"] = {
            "date": date.today().isoformat(),
            "games": games.get("GameHeader", [])[:20],
            "line_scores": games.get("LineScore", [])[:40],
        }
        result["success"] = True
        log(f"[OpenClaw] nba-stats: fetched {len(result['data']['games'])} games")
    except Exception as e:
        result["error"] = str(e)
        log(f"[OpenClaw] nba-stats fallback failed: {e}")
        # Final fallback: ask LiteLLM
        response = call_litellm(
            "You are an NBA stats expert. Provide today's game schedule and key stats.",
            "What NBA games are scheduled today? List teams, projected starters, and key injuries.",
            model="fast", max_tokens=1500,
        )
        if response:
            result["data"] = {"llm_analysis": response[:2000]}
            result["success"] = True
            result["source"] = "litellm-fallback"
    return result


def _run_openclaw_agent(agent_name, system_prompt, user_prompt, model_id=None):
    """
    Run a single OpenClaw agent task via OpenRouter API (or LiteLLM fallback).
    Returns the agent's response text.
    """
    if not model_id:
        model_id = OPENROUTER_MODEL_HEALER

    # Try OpenRouter directly if we have a key
    if OPENROUTER_API_KEY:
        import urllib.request
        body = json.dumps({
            "model": model_id.replace("openrouter/", ""),
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "max_tokens": 3000,
            "temperature": 0.3,
        }).encode()
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "HTTP-Referer": "https://nomos-nba-quant.hf.space",
            "X-Title": "NOMOS NBA Quant",
        }
        req = urllib.request.Request(f"{OPENROUTER_BASE_URL}/chat/completions", data=body, headers=headers)
        try:
            resp = urllib.request.urlopen(req, timeout=120)
            data = json.loads(resp.read().decode())
            choices = data.get("choices", [])
            if choices:
                return choices[0].get("message", {}).get("content", "")
        except Exception as e:
            log(f"[OpenClaw] OpenRouter call failed for {agent_name}: {e}")

    # Fallback to LiteLLM
    return call_litellm(system_prompt, user_prompt, model="smart", max_tokens=3000)


def openclaw_research_loop():
    """
    OpenClaw multi-agent research loop. Runs every 30 minutes.
    Orchestrates 4 agents: Research, Odds, Props, Evolution.
    Each agent writes results to data/results/openclaw-*.json.
    """
    log("[OpenClaw] === RESEARCH LOOP STARTING ===")
    evolution_state["openclaw_status"] = "RUNNING"
    ts = datetime.now(timezone.utc).isoformat()

    # ── Agent 1: Research Agent ──
    try:
        evolution_state["openclaw_agents"]["research"]["status"] = "RUNNING"
        log("[OpenClaw] Research Agent: searching latest NBA quant papers...")

        gen = evolution_state.get("generation", 0)
        brier = evolution_state.get("best_brier", 1.0)
        roi = evolution_state.get("best_roi", 0.0)

        research_response = _run_openclaw_agent(
            "research",
            """You are an elite NBA quantitative research analyst working for a hedge fund.
Your mission: find cutting-edge techniques for NBA prediction and sports betting alpha.
Focus on 2025-2026 developments. Be specific about implementation details.
Output JSON: {"techniques": [{"name": str, "description": str, "expected_improvement": str, "category": str}],
"market_insights": [str], "recommended_features": [str], "papers": [{"title": str, "key_finding": str}]}""",
            f"""Search for the latest NBA quantitative prediction research and techniques.

Current system: genetic evolution at generation {gen}, Brier={brier:.4f}, ROI={roi:.1%}
Using: XGBoost/LightGBM/CatBoost ensemble, ~580 feature candidates, walk-forward validation.

Find NEW alpha sources we're missing:
1. Market microstructure: CLV analysis, steam move detection, sharp money flow
2. Player tracking: spatial data, speed/distance metrics, shot quality models
3. Advanced ML: conformal prediction, graph neural networks, attention mechanisms
4. Alternative data: social media sentiment, referee tendencies, arena effects
5. Portfolio: Kelly criterion improvements, correlation-aware bet sizing""",
            model_id=OPENROUTER_MODEL_HEALER,
        )

        research_result = {
            "agent": "research",
            "timestamp": ts,
            "response": research_response,
            "generation": gen,
        }
        try:
            research_result["parsed"] = json.loads(research_response)
        except (json.JSONDecodeError, TypeError):
            research_result["parsed"] = None

        (RESULTS_DIR / "openclaw-research.json").write_text(
            json.dumps(research_result, indent=2, default=str)
        )
        evolution_state["openclaw_last_research"] = (research_response or "No response")[:500]
        evolution_state["openclaw_agents"]["research"]["status"] = "DONE"
        evolution_state["openclaw_agents"]["research"]["last_run"] = ts
        log(f"[OpenClaw] Research Agent: {len(research_response or '')} chars")
    except Exception as e:
        log(f"[OpenClaw] Research Agent error: {e}")
        evolution_state["openclaw_agents"]["research"]["status"] = f"ERROR: {e}"

    # ── Agent 2: Odds Agent ──
    try:
        evolution_state["openclaw_agents"]["odds"]["status"] = "RUNNING"
        log("[OpenClaw] Odds Agent: fetching live odds and line movements...")

        # First try the sports-odds skill
        odds_skill_result = run_openclaw_skill("sports-odds", {"sport": "basketball_nba"})

        # Then get LLM analysis of the odds
        odds_context = json.dumps(odds_skill_result.get("data", {}), default=str)[:2000]
        odds_response = _run_openclaw_agent(
            "odds",
            """You are a sports betting market analyst specializing in NBA odds and line movements.
Analyze odds data and detect patterns. Output JSON:
{"steam_moves": [{"game": str, "direction": str, "magnitude": float, "timestamp": str}],
"reverse_line_moves": [{"game": str, "public_side": str, "line_move": str}],
"sharp_indicators": [{"game": str, "signal": str, "confidence": float}],
"value_bets": [{"game": str, "side": str, "edge": float, "reasoning": str}],
"market_summary": str}""",
            f"""Analyze the current NBA betting market. Here is raw odds data:
{odds_context}

Identify:
1. Steam moves (sharp money causing 1+ point line shifts in minutes)
2. Reverse line movement (line moves opposite public betting %)
3. CLV opportunities (where our model might have closing line value)
4. Value bets where market is mispriced
5. Correlation between games (back-to-back, travel, etc.)""",
            model_id=OPENROUTER_MODEL_HUNTER,
        )

        odds_result = {
            "agent": "odds",
            "timestamp": ts,
            "skill_data": odds_skill_result.get("data"),
            "analysis": odds_response,
        }
        try:
            odds_result["parsed"] = json.loads(odds_response)
        except (json.JSONDecodeError, TypeError):
            odds_result["parsed"] = None

        (RESULTS_DIR / "openclaw-odds.json").write_text(
            json.dumps(odds_result, indent=2, default=str)
        )
        evolution_state["openclaw_last_odds"] = (odds_response or "No response")[:500]
        evolution_state["openclaw_agents"]["odds"]["status"] = "DONE"
        evolution_state["openclaw_agents"]["odds"]["last_run"] = ts
        log(f"[OpenClaw] Odds Agent: {len(odds_response or '')} chars")
    except Exception as e:
        log(f"[OpenClaw] Odds Agent error: {e}")
        evolution_state["openclaw_agents"]["odds"]["status"] = f"ERROR: {e}"

    # ── Agent 3: Props Agent ──
    try:
        evolution_state["openclaw_agents"]["props"]["status"] = "RUNNING"
        log("[OpenClaw] Props Agent: tracking player props and performance...")

        props_response = _run_openclaw_agent(
            "props",
            """You are an NBA player props analyst. Track individual player metrics and prop lines.
Output JSON: {"injury_report": [{"player": str, "team": str, "status": str, "impact": str}],
"prop_analysis": [{"player": str, "prop": str, "line": float, "recommendation": str, "edge": float}],
"trending_up": [{"player": str, "metric": str, "l5_avg": float, "season_avg": float}],
"trending_down": [{"player": str, "metric": str, "l5_avg": float, "season_avg": float}],
"matchup_edges": [{"player": str, "opponent": str, "advantage": str}]}""",
            """Analyze current NBA player props and performance trends.

Focus on:
1. Key injuries and their impact on spreads/totals
2. Players trending up/down in last 5 games vs season averages
3. Mispriced props based on recent form vs betting lines
4. Matchup advantages (e.g., fast PG vs slow defensive team)
5. Back-to-back fatigue impact on star players
6. Load management signals (minutes trending down)""",
            model_id=OPENROUTER_MODEL_HEALER,
        )

        props_result = {
            "agent": "props",
            "timestamp": ts,
            "analysis": props_response,
        }
        try:
            props_result["parsed"] = json.loads(props_response)
        except (json.JSONDecodeError, TypeError):
            props_result["parsed"] = None

        (RESULTS_DIR / "openclaw-props.json").write_text(
            json.dumps(props_result, indent=2, default=str)
        )
        evolution_state["openclaw_last_props"] = (props_response or "No response")[:500]
        evolution_state["openclaw_agents"]["props"]["status"] = "DONE"
        evolution_state["openclaw_agents"]["props"]["last_run"] = ts
        log(f"[OpenClaw] Props Agent: {len(props_response or '')} chars")
    except Exception as e:
        log(f"[OpenClaw] Props Agent error: {e}")
        evolution_state["openclaw_agents"]["props"]["status"] = f"ERROR: {e}"

    # ── Agent 4: Evolution Agent ──
    try:
        evolution_state["openclaw_agents"]["evolution"]["status"] = "RUNNING"
        log("[OpenClaw] Evolution Agent: analyzing genetic algorithm progress...")

        evo_context = json.dumps({
            "generation": evolution_state.get("generation", 0),
            "best_brier": evolution_state.get("best_brier", 1.0),
            "best_roi": evolution_state.get("best_roi", 0.0),
            "best_sharpe": evolution_state.get("best_sharpe", 0.0),
            "best_model_type": evolution_state.get("best_model_type", "none"),
            "n_features_selected": evolution_state.get("n_features_selected", 0),
            "n_feature_candidates": evolution_state.get("n_feature_candidates", 0),
            "population_size": evolution_state.get("population_size", 0),
            "diagnostics": evolution_state.get("diagnostics", []),
            "history": evolution_state.get("history", [])[-10:],
        }, default=str)

        evo_response = _run_openclaw_agent(
            "evolution",
            """You are a genetic algorithm optimization expert for NBA prediction models.
Analyze evolution progress, detect issues, recommend changes.
Output JSON: {"status_assessment": str, "stagnation_detected": bool,
"recommendations": [{"action": str, "priority": str, "expected_impact": str}],
"mutation_rate_suggestion": float, "crossover_suggestion": str,
"feature_suggestions": [str], "model_diversity_score": float}""",
            f"""Analyze the current state of our genetic evolution for NBA prediction:

{evo_context}

Assess:
1. Is the evolution progressing or stagnating?
2. Are we exploring the feature space sufficiently?
3. Should mutation rate increase/decrease?
4. Is the population diverse enough in model types?
5. Based on research findings, what new features should we introduce?
6. What's the expected timeline to reach Brier < 0.20?""",
            model_id=OPENROUTER_MODEL_HEALER,
        )

        evo_result = {
            "agent": "evolution",
            "timestamp": ts,
            "analysis": evo_response,
        }
        try:
            evo_result["parsed"] = json.loads(evo_response)
        except (json.JSONDecodeError, TypeError):
            evo_result["parsed"] = None

        (RESULTS_DIR / "openclaw-evolution.json").write_text(
            json.dumps(evo_result, indent=2, default=str)
        )
        evolution_state["openclaw_last_evolution"] = (evo_response or "No response")[:500]
        evolution_state["openclaw_agents"]["evolution"]["status"] = "DONE"
        evolution_state["openclaw_agents"]["evolution"]["last_run"] = ts
        log(f"[OpenClaw] Evolution Agent: {len(evo_response or '')} chars")
    except Exception as e:
        log(f"[OpenClaw] Evolution Agent error: {e}")
        evolution_state["openclaw_agents"]["evolution"]["status"] = f"ERROR: {e}"

    # ── Summary ──
    evolution_state["openclaw_status"] = "IDLE"
    evolution_state["openclaw_last_run"] = ts
    log("[OpenClaw] === RESEARCH LOOP COMPLETE ===")


def _openclaw_loop_forever():
    """Background thread: run openclaw_research_loop every 30 minutes."""
    # Initial setup
    setup_openclaw()

    # Wait 2 minutes for the main evolution loop to initialize
    log("[OpenClaw] Waiting 120s for evolution loop to initialize...")
    time.sleep(120)

    while True:
        try:
            openclaw_research_loop()
        except Exception as e:
            log(f"[OpenClaw] Loop error: {e}")
            log(traceback.format_exc()[-500:])
            evolution_state["openclaw_status"] = f"ERROR: {e}"

        # Sleep 30 minutes
        log("[OpenClaw] Next run in 30 minutes...")
        time.sleep(1800)


# ── LiteLLM Research Agent ──

# Model routing: logical names → actual model identifiers
# "healer" and "hunter" are FREE OpenRouter stealth models
MODEL_ROUTES = {
    "smart": "smart",                           # LiteLLM model group (13-provider fallback)
    "fast": "fast",                             # LiteLLM model group (quick tasks)
    "default": "default",                       # LiteLLM model group (fallback)
    "healer": "openrouter/healer-alpha",        # FREE, omni-modal, 262K context
    "hunter": "openrouter/hunter-alpha",        # FREE, 1T params, 100K context, best for agents
}


def call_litellm(system_prompt, user_prompt, model="smart", max_tokens=4000, temperature=0.3):
    """Call LiteLLM proxy (S7) for research tasks.

    Model routing:
      - "smart" / "fast" / "default" → existing LiteLLM model groups
      - "healer" → openrouter/healer-alpha (FREE, omni-modal, 262K context)
      - "hunter" → openrouter/hunter-alpha (FREE, 1T params, 100K context, best for agents)
    """
    import urllib.request

    # Resolve model name through routing table
    resolved_model = MODEL_ROUTES.get(model, model)

    body = json.dumps({
        "model": resolved_model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "max_tokens": max_tokens,
        "temperature": temperature,
    }).encode()

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {LITELLM_KEY}",
    }
    req = urllib.request.Request(f"{LITELLM_URL}/v1/chat/completions", data=body, headers=headers)
    try:
        resp = urllib.request.urlopen(req, timeout=180)
        data = json.loads(resp.read().decode())
        choices = data.get("choices", [])
        if choices:
            return choices[0].get("message", {}).get("content", "")
        return ""
    except Exception as e:
        log(f"LiteLLM call failed (model={resolved_model}): {e}")
        return ""


def call_kimi(system_prompt, user_prompt, model="moonshot-v1-8k", max_tokens=4000, temperature=0.3):
    """Call Kimi / Moonshot AI API (OpenAI-compatible) as second research agent."""
    if not KIMI_API_KEY:
        log("[Kimi] No API key configured, skipping")
        return ""
    import urllib.request
    body = json.dumps({
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "max_tokens": max_tokens,
        "temperature": temperature,
    }).encode()
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {KIMI_API_KEY}",
    }
    req = urllib.request.Request(f"{KIMI_BASE_URL}/chat/completions", data=body, headers=headers)
    try:
        resp = urllib.request.urlopen(req, timeout=120)
        data = json.loads(resp.read().decode())
        choices = data.get("choices", [])
        if choices:
            return choices[0].get("message", {}).get("content", "")
        return ""
    except Exception as e:
        log(f"[Kimi] Call failed: {e}")
        return ""


def research_nba_quant(generation):
    """
    LiteLLM research agent: search for latest 2026 NBA quant papers
    and market microstructure techniques.
    """
    log(f"[Research Agent] Gen {generation} — Querying latest NBA quant research...")

    system_prompt = """You are an expert NBA quantitative analyst and sports betting researcher.
Your job is to identify cutting-edge techniques from the latest academic papers and industry practice.
Focus on 2025-2026 developments. Be specific about implementation details.
Output JSON with keys: techniques (list of {name, description, expected_brier_improvement, implementation_difficulty, category}), market_insights (list of strings), recommended_features (list of strings)."""

    user_prompt = f"""Research the latest developments in NBA prediction and sports betting quantitative analysis (2025-2026).

Focus areas:
1. **Market Microstructure**: CLV (Closing Line Value) analysis, line movement patterns, steam moves, reverse line movement, sharp money indicators
2. **Advanced ML**: Uncertainty-aware models (MC Dropout, conformal prediction), graph neural networks for player interactions, attention-based temporal models
3. **Feature Engineering**: Pace-adjusted metrics, travel fatigue models (haversine distance), rest day impact, strength of schedule quality, clutch performance
4. **Calibration**: Temperature scaling, Platt scaling, beta calibration, ensemble calibration techniques
5. **Portfolio Theory**: Kelly criterion with uncertainty, fractional Kelly, simultaneous correlated bets, bankroll management with drawdown control

Current system state:
- Generation: {generation}
- Using genetic algorithm to evolve feature subsets + hyperparameters
- ~580 feature candidates across 10 categories
- Walk-forward backtesting with ROI + Brier + Sharpe fitness

What NEW techniques should we explore? What are the biggest alpha opportunities?"""

    # Primary research: Hunter Alpha (FREE, 1T params, best for agentic research)
    response = call_litellm(system_prompt, user_prompt, model="hunter", max_tokens=3000)

    # Secondary research: Kimi for second opinion
    kimi_response = call_kimi(
        system_prompt,
        user_prompt.replace("Research the latest", "As a second research agent, independently research the latest"),
        model="moonshot-v1-8k",
        max_tokens=2000,
    )

    # Third research: Healer Alpha (FREE, omni-modal, 262K context) for cross-validation
    healer_prompt = f"""Cross-validate these NBA quant research findings from two other agents.
Identify what they AGREE on (high confidence), what they DISAGREE on (needs more research),
and what they both MISSED (blind spots).

Agent 1 (Hunter Alpha) findings:
{(response or 'No response')[:2000]}

Agent 2 (Kimi) findings:
{(kimi_response or 'No response')[:1500]}

Output JSON with keys: consensus (list of agreed techniques), disagreements (list of disputed points),
blind_spots (list of missed areas), final_recommendations (top 5 prioritized actions)."""

    healer_response = call_litellm(
        "You are a senior NBA quant research reviewer. Cross-validate findings from multiple research agents.",
        healer_prompt,
        model="healer",
        max_tokens=2500,
    )

    if response or kimi_response or healer_response:
        log(f"[Research Agent] Hunter: {len(response)} chars, Kimi: {len(kimi_response)} chars, Healer: {len(healer_response)} chars")
        findings = {
            "generation": generation,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "hunter_response": response,
            "kimi_response": kimi_response,
            "healer_crossval": healer_response,
        }
        for key, resp in [("hunter_parsed", response), ("kimi_parsed", kimi_response), ("healer_parsed", healer_response)]:
            try:
                findings[key] = json.loads(resp)
            except (json.JSONDecodeError, TypeError):
                findings[key] = None

        out = RESULTS_DIR / "research-findings.json"
        out.write_text(json.dumps(findings, indent=2, default=str))

        combined = (response or "")[:250] + "\n---KIMI---\n" + (kimi_response or "")[:150] + "\n---HEALER---\n" + (healer_response or "")[:150]
        evolution_state["research_summary"] = combined[:600]
        return findings
    else:
        log("[Research Agent] No response from any of Hunter/Kimi/Healer")
        return None


def run_self_diagnostic(evo_loop, generation):
    """
    Self-diagnostic: analyze weaknesses in the current evolution state.
    Runs every 5 generations as configured.
    """
    log(f"[Self-Diagnostic] Gen {generation} — Analyzing system weaknesses...")

    issues = []
    best = evo_loop.best_ever

    if best is None:
        issues.append("NO BEST MODEL YET — population has not been evaluated")
        evolution_state["diagnostics"] = issues
        return issues

    # Core fitness checks
    if best.fitness.get("brier", 1.0) > 0.24:
        issues.append(f"BRIER={best.fitness['brier']:.4f} > 0.24 — barely better than baseline 0.25")
    if best.fitness.get("roi", 0.0) < 0.0:
        issues.append(f"ROI={best.fitness['roi']:.1%} — model LOSES money on value bets")
    if best.fitness.get("calibration", 1.0) > 0.05:
        issues.append(f"Calibration error={best.fitness['calibration']:.3f} > 5% — probabilities unreliable")
    if best.fitness.get("sharpe", 0.0) < 0.5:
        issues.append(f"Sharpe={best.fitness['sharpe']:.2f} < 0.5 — poor risk-adjusted returns")

    # Feature diversity checks
    n_feats = best.n_features
    if n_feats < 100:
        issues.append(f"Only {n_feats} features selected — try wider feature search")
    if n_feats > 300:
        issues.append(f"{n_feats} features — potential overfitting, increase mutation pressure")

    # Check feature category distribution
    selected = best.selected_indices()
    feature_names = evo_loop.feature_engine.feature_names
    categories = {"market": 0, "schedule": 0, "matchup": 0, "efficiency": 0, "other": 0}
    for idx in selected:
        if idx < len(feature_names):
            name = feature_names[idx]
            if any(k in name for k in ("market", "spread", "clv", "steam", "line")):
                categories["market"] += 1
            elif any(k in name for k in ("rest", "travel", "fatigue", "b2b")):
                categories["schedule"] += 1
            elif any(k in name for k in ("elo", "h2h", "matchup")):
                categories["matchup"] += 1
            elif any(k in name for k in ("efg", "ortg", "pace", "four_factor")):
                categories["efficiency"] += 1
            else:
                categories["other"] += 1

    if categories["market"] == 0:
        issues.append("ZERO market features — missing microstructure alpha source!")
    if categories["schedule"] < 5:
        issues.append(f"Only {categories['schedule']} schedule features — travel/fatigue edge missed")
    if categories["efficiency"] < 10:
        issues.append(f"Only {categories['efficiency']} efficiency features — core signal weak")

    # Population diversity check
    model_types = [ind.hyperparams.get("model_type", "?") for ind in evo_loop.population]
    unique_types = set(model_types)
    if len(unique_types) < 2:
        issues.append(f"Population converged to single model type: {unique_types} — need more diversity")

    # Convergence check
    if len(evo_loop.history) >= 10:
        recent = evo_loop.history[-10:]
        composites = [h["best_composite"] for h in recent]
        improvement = composites[-1] - composites[0]
        if improvement < 0.001:
            issues.append(f"Stagnant: only {improvement:.4f} improvement over 10 generations — increase mutation rate")

    if issues:
        log(f"[Self-Diagnostic] {len(issues)} issues found:")
        for issue in issues:
            log(f"  - {issue}")

        # Ask LLM for recommendations based on issues
        rec_prompt = f"""Our NBA prediction genetic evolution system has these issues at generation {generation}:
{chr(10).join(f'- {i}' for i in issues)}

Feature category distribution: {json.dumps(categories)}
Current best Brier: {best.fitness.get('brier', 1.0):.4f}
Current best ROI: {best.fitness.get('roi', 0.0):.1%}
Model type: {best.hyperparams.get('model_type', 'unknown')}
Features selected: {n_feats}

Suggest 3 specific, actionable fixes. Be concise."""

        recs = call_litellm(
            "You are an expert ML/quant advisor. Give specific actionable recommendations.",
            rec_prompt,
            model="hunter",  # Hunter Alpha: FREE, 1T params — better diagnostic quality at zero cost
            max_tokens=1000,
        )
        if recs:
            log(f"[Self-Diagnostic] LLM Recommendations: {recs[:300]}")
            issues.append(f"LLM RECS: {recs[:500]}")
    else:
        log("[Self-Diagnostic] No issues found — system healthy")

    evolution_state["diagnostics"] = issues[-10:]
    return issues


# ── Main Evolution Orchestrator Loop ──

def evolution_orchestrator_loop():
    """
    Main loop: run genetic evolution 24/7 with periodic research + diagnostics.

    Cycle:
    1. INITIALIZE — Load data, create population
    2. EVOLVE — Run N generations per cycle
    3. RESEARCH — LiteLLM searches latest papers (every 10 gens)
    4. DIAGNOSTIC — Self-analysis of weaknesses (every 5 gens)
    5. SAVE — Persist results to disk
    6. REPEAT
    """
    log("=== GENETIC EVOLUTION ORCHESTRATOR STARTING ===")

    # Import evolution modules
    sys.path.insert(0, "/app")
    try:
        from evolution.loop import EvolutionLoop
        log("EvolutionLoop imported successfully")
    except ImportError as e:
        log(f"CRITICAL: Cannot import EvolutionLoop: {e}")
        log("Falling back to standalone mode...")
        evolution_state["status"] = f"IMPORT ERROR: {e}"
        return

    # Initialize evolution loop
    try:
        evo_loop = EvolutionLoop(
            data_dir=DATA_DIR,
            results_dir=RESULTS_DIR,
        )
        evolution_state["n_feature_candidates"] = evo_loop.n_feature_candidates
        evolution_state["status"] = "LOADING DATA"
        log(f"Feature engine: {evo_loop.n_feature_candidates} candidates")
    except Exception as e:
        log(f"CRITICAL: EvolutionLoop init failed: {e}")
        log(traceback.format_exc()[-500:])
        evolution_state["status"] = f"INIT ERROR: {e}"
        return

    # Load game data
    try:
        games = evo_loop.load_data()
        evolution_state["games_loaded"] = len(games)
        log(f"Games loaded: {len(games)}")
    except Exception as e:
        log(f"Error loading games: {e}")
        evolution_state["status"] = f"DATA ERROR: {e}"
        return

    if len(games) < 100:
        log(f"Only {len(games)} games — need at least 100 for evolution")
        evolution_state["status"] = f"INSUFFICIENT DATA ({len(games)} games)"
        # Still try to run with what we have, or wait for data
        if len(games) < 10:
            log("FATAL: Not enough data. Waiting for data ingestion...")
            return

    # Build feature matrix
    try:
        evolution_state["status"] = "BUILDING FEATURES"
        log("Building feature matrix...")
        X, y, feature_names = evo_loop.feature_engine.build(games)
        log(f"Feature matrix: {X.shape[0]} samples x {X.shape[1]} features")
    except Exception as e:
        log(f"Feature build error: {e}")
        log(traceback.format_exc()[-500:])
        evolution_state["status"] = f"FEATURE ERROR: {e}"
        return

    # Initialize population
    try:
        evo_loop.initialize_population()
        evolution_state["population_size"] = len(evo_loop.population)
        log(f"Population initialized: {len(evo_loop.population)} individuals")
    except Exception as e:
        log(f"Population init error: {e}")
        evolution_state["status"] = f"POP ERROR: {e}"
        return

    # ── Continuous Evolution ──
    cycle = 0
    GENS_PER_CYCLE = 10  # Run 10 generations, then pause for research/diagnostic/save

    while True:
        cycle += 1
        evolution_state["cycle"] = cycle
        evolution_state["status"] = "EVOLVING"

        log(f"\n{'='*60}")
        log(f"EVOLUTION CYCLE #{cycle} — Starting {GENS_PER_CYCLE} generations")
        log(f"{'='*60}")

        for gen_in_cycle in range(GENS_PER_CYCLE):
            try:
                start = time.time()
                evo_loop.evolve_generation(X, y)
                elapsed = time.time() - start

                # Update shared state
                best = evo_loop.best_ever
                if best:
                    evolution_state["generation"] = evo_loop.generation
                    evolution_state["best_brier"] = best.fitness.get("brier", 1.0)
                    evolution_state["best_roi"] = best.fitness.get("roi", 0.0)
                    evolution_state["best_sharpe"] = best.fitness.get("sharpe", 0.0)
                    evolution_state["best_composite"] = best.fitness.get("composite", 0.0)
                    evolution_state["best_model_type"] = best.hyperparams.get("model_type", "?")
                    evolution_state["n_features_selected"] = best.n_features
                    evolution_state["history"] = evo_loop.history[-20:]

                log(f"Gen {evo_loop.generation}: "
                    f"Brier={evolution_state['best_brier']:.4f} "
                    f"ROI={evolution_state['best_roi']:.1%} "
                    f"Sharpe={evolution_state['best_sharpe']:.2f} "
                    f"Features={evolution_state['n_features_selected']} "
                    f"({elapsed:.1f}s)")

            except Exception as e:
                log(f"Generation error: {e}")
                log(traceback.format_exc()[-300:])
                continue

        # ── Periodic Research (every 10 generations) ──
        if evo_loop.generation > 0 and evo_loop.generation % 10 == 0:
            evolution_state["status"] = "RESEARCHING"
            try:
                research_thread = threading.Thread(
                    target=research_nba_quant,
                    args=(evo_loop.generation,),
                    daemon=True,
                )
                research_thread.start()
                research_thread.join(timeout=180)  # 3 min max for research
            except Exception as e:
                log(f"Research error: {e}")

        # ── Self-Diagnostic (every 5 generations) ──
        if evo_loop.generation > 0 and evo_loop.generation % 5 == 0:
            evolution_state["status"] = "DIAGNOSTIC"
            try:
                run_self_diagnostic(evo_loop, evo_loop.generation)
            except Exception as e:
                log(f"Diagnostic error: {e}")

        # ── Save Results ──
        evolution_state["status"] = "SAVING"
        try:
            evo_loop.save_results()
            log(f"Results saved — Gen {evo_loop.generation}")
        except Exception as e:
            log(f"Save error: {e}")

        # ── Sync summary to swarm-status.json (for external consumption) ──
        try:
            status = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "system": "genetic-evolution",
                "cycle": cycle,
                "generation": evo_loop.generation,
                "best_brier": evolution_state["best_brier"],
                "best_roi": evolution_state["best_roi"],
                "best_sharpe": evolution_state["best_sharpe"],
                "best_composite": evolution_state["best_composite"],
                "best_model_type": evolution_state["best_model_type"],
                "n_features_selected": evolution_state["n_features_selected"],
                "n_feature_candidates": evolution_state["n_feature_candidates"],
                "population_size": evolution_state["population_size"],
                "games_loaded": evolution_state["games_loaded"],
                "diagnostics": evolution_state["diagnostics"],
            }
            (RESULTS_DIR / "swarm-status.json").write_text(json.dumps(status, indent=2, default=str))
        except Exception as e:
            log(f"Status sync error: {e}")

        # Brief pause between cycles
        evolution_state["status"] = "COOLDOWN"
        log(f"Cycle #{cycle} done — cooling down 60s before next cycle...")
        time.sleep(60)


# ── Gradio Dashboard ──

def get_dashboard():
    s = evolution_state
    gen = s["generation"]
    brier = s["best_brier"]
    roi = s["best_roi"]
    sharpe = s["best_sharpe"]
    composite = s["best_composite"]
    model = s["best_model_type"]
    n_feats = s["n_features_selected"]
    n_cands = s["n_feature_candidates"]
    pop = s["population_size"]
    games = s["games_loaded"]
    status = s["status"]
    cycle = s["cycle"]

    lines = [
        "# NOMOS NBA QUANT AI — Genetic Evolution Dashboard",
        "",
        "## System Status",
        f"- **Status**: {status}",
        f"- **Cycle**: {cycle} | **Generation**: {gen}",
        f"- **Games Loaded**: {games:,}",
        f"- **Population**: {pop} individuals",
        f"- **Feature Candidates**: {n_cands}",
        "",
        "## Best Individual (All-Time)",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Brier Score | **{brier:.4f}** (lower = better, baseline 0.25) |",
        f"| ROI | **{roi:.1%}** (positive = profitable) |",
        f"| Sharpe Ratio | **{sharpe:.2f}** (>1 = good) |",
        f"| Composite Fitness | **{composite:.4f}** |",
        f"| Model Type | **{model}** |",
        f"| Features Selected | **{n_feats}** / {n_cands} |",
        "",
    ]

    # Evolution history chart (text-based)
    history = s.get("history", [])
    if history:
        lines.append("## Evolution Progress (last 20 gens)")
        lines.append("| Gen | Brier | ROI | Features | Model | Composite |")
        lines.append("|-----|-------|-----|----------|-------|-----------|")
        for h in history[-20:]:
            lines.append(
                f"| {h.get('generation', '?')} "
                f"| {h.get('best_brier', 0):.4f} "
                f"| {h.get('best_roi', 0):.1%} "
                f"| {h.get('n_features', '?')} "
                f"| {h.get('model_type', '?')} "
                f"| {h.get('best_composite', 0):.4f} |"
            )
        lines.append("")

    # Diagnostics
    diags = s.get("diagnostics", [])
    if diags:
        lines.append("## Self-Diagnostic Issues")
        for d in diags[-5:]:
            lines.append(f"- {d[:200]}")
        lines.append("")

    # Research
    research = s.get("research_summary", "")
    if research and research != "No research yet":
        lines.append("## Latest Research Findings")
        lines.append(f"```\n{research[:600]}\n```")

    return "\n".join(lines)


def get_logs():
    return "\n".join(list(improvement_log)[-100:])


def get_research():
    try:
        f = RESULTS_DIR / "research-findings.json"
        if f.exists():
            data = json.loads(f.read_text())
            return json.dumps(data, indent=2, default=str)[:5000]
    except Exception:
        pass
    return "No research findings yet."


def get_evolution_json():
    try:
        f = RESULTS_DIR / "evolution-status.json"
        if f.exists():
            return f.read_text()[:10000]
    except Exception:
        pass
    return "{}"


# ── OpenClaw Dashboard Functions ──

def get_openclaw_dashboard():
    """Generate OpenClaw multi-agent status dashboard."""
    s = evolution_state
    oc_status = s.get("openclaw_status", "NOT INITIALIZED")
    oc_last_run = s.get("openclaw_last_run", "Never")
    agents = s.get("openclaw_agents", {})

    lines = [
        "# OpenClaw Multi-Agent Dashboard",
        "",
        f"**Status**: {oc_status} | **Last Run**: {oc_last_run}",
        "",
        "## Agent Status",
        "| Agent | Status | Model | Last Run |",
        "|-------|--------|-------|----------|",
    ]

    agent_order = ["research", "odds", "props", "evolution"]
    agent_labels = {
        "research": "Research Agent",
        "odds": "Odds Agent",
        "props": "Props Agent",
        "evolution": "Evolution Agent",
    }

    for agent_key in agent_order:
        info = agents.get(agent_key, {"status": "N/A", "model": "N/A", "last_run": "Never"})
        status_icon = "RUNNING" if info.get("status") == "RUNNING" else info.get("status", "N/A")
        lines.append(
            f"| {agent_labels.get(agent_key, agent_key)} "
            f"| {status_icon} "
            f"| `{info.get('model', 'N/A')}` "
            f"| {info.get('last_run', 'Never')[:19]} |"
        )

    lines.extend([
        "",
        "## Configuration",
        f"- **OpenRouter Key**: {'SET' if OPENROUTER_API_KEY else 'NOT SET (using LiteLLM fallback)'}",
        f"- **Healer Alpha**: `{OPENROUTER_MODEL_HEALER}`",
        f"- **Hunter Alpha**: `{OPENROUTER_MODEL_HUNTER}`",
        f"- **Config Path**: `{OPENCLAW_CONFIG}`",
        f"- **Loop Interval**: 30 minutes",
        "",
        "## Skills",
        "| Skill | Description |",
        "|-------|-------------|",
        "| `sports-odds` | Fetches live NBA odds (the-odds-api / LiteLLM fallback) |",
        "| `nba-stats` | Fetches NBA stats (nba_api / LiteLLM fallback) |",
    ])

    return "\n".join(lines)


def get_openclaw_research():
    """Get latest OpenClaw research findings."""
    try:
        f = RESULTS_DIR / "openclaw-research.json"
        if f.exists():
            data = json.loads(f.read_text())
            return json.dumps(data, indent=2, default=str)[:5000]
    except Exception:
        pass

    # Fall back to state
    research = evolution_state.get("openclaw_last_research", "None")
    if research and research != "None":
        return research
    return "No OpenClaw research findings yet. First run starts ~2 minutes after boot."


def get_openclaw_odds():
    """Get latest OpenClaw odds data."""
    try:
        f = RESULTS_DIR / "openclaw-odds.json"
        if f.exists():
            data = json.loads(f.read_text())
            return json.dumps(data, indent=2, default=str)[:5000]
    except Exception:
        pass

    odds = evolution_state.get("openclaw_last_odds", "None")
    if odds and odds != "None":
        return odds
    return "No OpenClaw odds data yet. First run starts ~2 minutes after boot."


def get_openclaw_props():
    """Get latest OpenClaw props data."""
    try:
        f = RESULTS_DIR / "openclaw-props.json"
        if f.exists():
            data = json.loads(f.read_text())
            return json.dumps(data, indent=2, default=str)[:5000]
    except Exception:
        pass

    props = evolution_state.get("openclaw_last_props", "None")
    if props and props != "None":
        return props
    return "No OpenClaw props data yet. First run starts ~2 minutes after boot."


def get_openclaw_evolution():
    """Get latest OpenClaw evolution agent analysis."""
    try:
        f = RESULTS_DIR / "openclaw-evolution.json"
        if f.exists():
            data = json.loads(f.read_text())
            return json.dumps(data, indent=2, default=str)[:5000]
    except Exception:
        pass

    evo = evolution_state.get("openclaw_last_evolution", "None")
    if evo and evo != "None":
        return evo
    return "No OpenClaw evolution analysis yet. First run starts ~2 minutes after boot."


def trigger_openclaw_manual():
    """Manually trigger an OpenClaw research loop (runs in background)."""
    t = threading.Thread(target=openclaw_research_loop, daemon=True, name="OpenClawManual")
    t.start()
    return "OpenClaw research loop triggered. Refresh in ~2 minutes to see results."


# ── Gradio Dashboard ──

with gr.Blocks(title="NOMOS NBA QUANT — Genetic Evolution", theme=gr.themes.Monochrome()) as app:
    gr.Markdown("# NOMOS NBA QUANT AI — Genetic Evolution Engine")
    gr.Markdown("*Population of 50 models evolving 24/7 via genetic algorithm + OpenClaw multi-agent research*")

    with gr.Tabs():
        # ── Tab 1: Evolution Dashboard ──
        with gr.TabItem("Evolution"):
            with gr.Row():
                with gr.Column(scale=2):
                    dashboard_md = gr.Markdown(get_dashboard)
                    refresh_btn = gr.Button("Refresh Dashboard")
                    refresh_btn.click(get_dashboard, outputs=dashboard_md)

                with gr.Column(scale=3):
                    logs_box = gr.Textbox(label="Evolution Logs", value=get_logs, lines=25, max_lines=30)
                    refresh_logs_btn = gr.Button("Refresh Logs")
                    refresh_logs_btn.click(get_logs, outputs=logs_box)

            with gr.Row():
                with gr.Column():
                    research_box = gr.Textbox(label="Research Findings", value=get_research, lines=15, max_lines=20)
                    refresh_research_btn = gr.Button("Refresh Research")
                    refresh_research_btn.click(get_research, outputs=research_box)

                with gr.Column():
                    evo_json_box = gr.Textbox(label="Evolution Status (JSON)", value=get_evolution_json, lines=15, max_lines=20)
                    refresh_evo_btn = gr.Button("Refresh Evolution Data")
                    refresh_evo_btn.click(get_evolution_json, outputs=evo_json_box)

        # ── Tab 2: OpenClaw Multi-Agent ──
        with gr.TabItem("OpenClaw Agents"):
            with gr.Row():
                with gr.Column(scale=2):
                    oc_dashboard_md = gr.Markdown(get_openclaw_dashboard)
                    with gr.Row():
                        oc_refresh_btn = gr.Button("Refresh")
                        oc_trigger_btn = gr.Button("Trigger Research Loop Now", variant="primary")
                    oc_refresh_btn.click(get_openclaw_dashboard, outputs=oc_dashboard_md)
                    oc_manual_status = gr.Textbox(label="Manual Trigger Status", lines=2, max_lines=3)
                    oc_trigger_btn.click(trigger_openclaw_manual, outputs=oc_manual_status)

                with gr.Column(scale=3):
                    oc_research_box = gr.Textbox(
                        label="Research Agent Findings",
                        value=get_openclaw_research,
                        lines=20, max_lines=25,
                    )
                    oc_research_refresh = gr.Button("Refresh Research")
                    oc_research_refresh.click(get_openclaw_research, outputs=oc_research_box)

            with gr.Row():
                with gr.Column():
                    oc_odds_box = gr.Textbox(
                        label="Odds Agent - Live Odds & Line Movements",
                        value=get_openclaw_odds,
                        lines=15, max_lines=20,
                    )
                    oc_odds_refresh = gr.Button("Refresh Odds")
                    oc_odds_refresh.click(get_openclaw_odds, outputs=oc_odds_box)

                with gr.Column():
                    oc_props_box = gr.Textbox(
                        label="Props Agent - Player Performance & Props",
                        value=get_openclaw_props,
                        lines=15, max_lines=20,
                    )
                    oc_props_refresh = gr.Button("Refresh Props")
                    oc_props_refresh.click(get_openclaw_props, outputs=oc_props_box)

            with gr.Row():
                with gr.Column():
                    oc_evo_box = gr.Textbox(
                        label="Evolution Agent - GA Analysis & Recommendations",
                        value=get_openclaw_evolution,
                        lines=15, max_lines=20,
                    )
                    oc_evo_refresh = gr.Button("Refresh Evolution Analysis")
                    oc_evo_refresh.click(get_openclaw_evolution, outputs=oc_evo_box)

    # Auto-refresh every 30s
    timer = gr.Timer(30)
    timer.tick(get_dashboard, outputs=dashboard_md)
    timer.tick(get_logs, outputs=logs_box)
    timer.tick(get_openclaw_dashboard, outputs=oc_dashboard_md)


# ── Launch threads at module level (HF Spaces imports, doesn't run __main__) ──

# Thread 1: Genetic evolution loop
_evo_thread = threading.Thread(target=evolution_orchestrator_loop, daemon=True, name="EvolutionLoop")
_evo_thread.start()
log("Genetic evolution orchestrator thread started (module-level)")

# Thread 2: OpenClaw multi-agent research loop (every 30 min)
_openclaw_thread = threading.Thread(target=_openclaw_loop_forever, daemon=True, name="OpenClawLoop")
_openclaw_thread.start()
log("OpenClaw multi-agent research loop thread started (module-level)")

if __name__ == "__main__":
    app.launch(server_name="0.0.0.0", server_port=7860, share=False)
