#!/bin/bash
################################################################################
# Department Council Runner — Karpathy loop per department
# Generated by Forge v19 init-repo-forge.sh
# Usage: department-council.sh <dept> [--dry-run]
################################################################################

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FORGE_COUNCIL="$REPO_ROOT/scripts/forge/council-template.py"
DEPT="${1:-}"
DRY_RUN="${2:-}"

source "$REPO_ROOT/.env.local" 2>/dev/null || true
source "/home/termius/mon-ipad/.env.local" 2>/dev/null || true

if [ -z "$DEPT" ]; then
    echo "Usage: $0 <department> [--dry-run]"
    echo "Departments: research engineering evolution product business evaluation infra finance"
    exit 1
fi

# Use shared forge council from mon-ipad if local doesn't exist
if [ ! -f "$FORGE_COUNCIL" ]; then
    FORGE_COUNCIL="/home/termius/mon-ipad/scripts/forge/council-template.py"
fi

ARGS="--repo $REPO_ROOT --dept $DEPT"
[ "$DRY_RUN" = "--dry-run" ] && ARGS="$ARGS --dry-run"

exec python3 "$FORGE_COUNCIL" $ARGS
